# Noctalia Theme for Mango
# Generated automatically by Noctalia

rootcolor = 0x242120ff
bordercolor = 0x746965ff
dropcolor = 0x8ba37e80
splitcolor = 0xcb9168ff
focuscolor = 0x8ba37eff
maximizescreencolor = 0xa69680ff
urgentcolor = 0xc6685dff
scratchpadcolor = 0xcb9168ff
globalcolor = 0x324727ff
overlaycolor = 0x4b3c28ff
jump_label_decorate_fg_color = 0xe5dec9ff
jump_label_decorate_bg_color = 0x413b38ff
jump_label_decorate_focus_fg_color = 0x242120ff
jump_label_decorate_focus_bg_color = 0x8ba37eff
jump_label_decorate_border_color = 0x746965ff
group_bar_decorate_fg_color = 0xe5dec9ff
group_bar_decorate_bg_color = 0x413b38ff
group_bar_decorate_focus_fg_color = 0x242120ff
group_bar_decorate_focus_bg_color = 0x8ba37eff
group_bar_decorate_border_color = 0x746965ff
