# ==================================================
# KEYBINDS (Atajos generales)
# ==================================================
bind=SUPER,Return,spawn,foot
bind=ALT,w,spawn,/home/ezequiel/.local/bin/helium
bind=SUPER,w,spawn,librewolf
bind=SUPER,e,spawn,pcmanfm-qt
bind=SUPER+SHIFT,v,spawn,foot -e hx
bind=SUPER+SHIFT,o,spawn,foot -e /home/ezequiel/.nix-profile/bin/concord
bind=SUPER,q,killclient,
bind=SUPER+SHIFT,r,reload_config


bind=SUPER+CTRL,s,spawn,/home/ezequiel/.config/sway/scripts/screenrecord-area.sh
bind=CTRL,p,spawn,/home/ezequiel/.config/sway/scripts/screenrecord-full.sh

bind=SUPER+SHIFT,s,spawn,/home/ezequiel/.config/sway/scripts/screenshot-area.sh
bind=SUPER,p,spawn,/home/ezequiel/.config/sway/scripts/screenshot-full.sh


bind=SUPER,space,spawn,noctalia msg panel-toggle launcher
bind=SUPER,s,spawn,noctalia msg panel-toggle control-center
bind=SUPER,comma,spawn,noctalia msg settings-toggle
bind=SUPER+SHIFT,t,spawn,noctalia msg panel-toggle wallpaper
bind=SUPER+SHIFT,b,spawn,noctalia msg bar-toggle
bind=CTRL+ALT,Delete,spawn,noctalia msg panel-toggle session
bind=CTRL+SUPER,r,spawn,noctalia msg config-reload

bind=NONE,XF86AudioRaiseVolume,spawn,noctalia msg volume-up
bind=NONE,XF86AudioLowerVolume,spawn,noctalia msg volume-down
bind=NONE,XF86AudioMute,spawn,noctalia msg volume-mute
bind=NONE,XF86MonBrightnessUp,spawn,noctalia msg brightness-up
bind=NONE,XF86MonBrightnessDown,spawn,noctalia msg brightness-down

bind=NONE,XF86AudioPlay,spawn,noctalia msg media toggle
bind=NONE,XF86AudioNext,spawn,noctalia msg media next
bind=NONE,XF86AudioPrev,spawn,noctalia msg media previous
bind=NONE,XF86AudioStop,spawn,noctalia msg media stop

bind=SUPER,f,togglefullscreen,
bind=SUPER+ALT,space,togglefloating,
bind=SUPER+SHIFT,minus,toggle_scratchpad

bind=ALT,Tab,focusstack,next
bind=ALT+SHIFT,Tab,focusstack,prev

bind=SUPER,h,focusdir,left
bind=SUPER,j,focusdir,down
bind=SUPER,k,focusdir,up
bind=SUPER,l,focusdir,right
bind=SUPER,Left,focusdir,left
bind=SUPER,Down,focusdir,down
bind=SUPER,Up,focusdir,up
bind=SUPER,Right,focusdir,right

bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,j,exchange_client,down
bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,l,exchange_client,right
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Right,exchange_client,right

bind=SUPER+CTRL,Left,viewtoleft,0
bind=SUPER+CTRL,Right,viewtoright,0

bind=CTRL+ALT,h,resizewin,-10,0
bind=CTRL+ALT,j,resizewin,0,10
bind=CTRL+ALT,k,resizewin,0,-10
bind=CTRL+ALT,l,resizewin,10,0
bind=CTRL+ALT,Left,resizewin,-10,0
bind=CTRL+ALT,Down,resizewin,0,10
bind=CTRL+ALT,Up,resizewin,0,-10
bind=CTRL+ALT,Right,resizewin,10,0

# Mouse binds
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize
bind=SUPER,Tab,spawn,noctalia msg window-switcher
