# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadowscolor = 0x000000ff
rootcolor = 0x242120ff
bordercolor = 0x746965ff
dropcolor = 0xcb916880
splitcolor = 0x8da388ff
focuscolor = 0xcb9168ff
maximizescreencolor = 0xa69680ff
urgentcolor = 0xc6685dff
scratchpadcolor = 0x8da388ff
globalcolor = 0x693917ff
overlaycolor = 0x4d3d27ff
jump_label_decorate_fg_color = 0xe5dec9ff
jump_label_decorate_bg_color = 0x413b38ff
jump_label_decorate_focus_fg_color = 0x242120ff
jump_label_decorate_focus_bg_color = 0xcb9168ff
jump_label_decorate_border_color = 0x746965ff
group_bar_decorate_fg_color = 0xe5dec9ff
group_bar_decorate_bg_color = 0x413b38ff
group_bar_decorate_focus_fg_color = 0x242120ff
group_bar_decorate_focus_bg_color = 0xcb9168ff
group_bar_decorate_border_color = 0x746965ff
