# ============================================
# ENTORNO (ENVIRONMENT VARIABLES)
# ============================================
env=XDG_CURRENT_DESKTOP,sway
env=XDG_SESSION_TYPE,wayland
env=XDG_SESSION_DESKTOP,sway
env=QT_QPA_PLATFORM,wayland;xcb
env=QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env=GDK_BACKEND,wayland,x11

# ============================================
# INPUT SETTINGS
# ============================================
xkb_rules_layout=latam,us
xkb_rules_variant=,altgr-intl
xkb_rules_options=grp:alt_shift_toggle
repeat_rate=50
repeat_delay=300

# Mouse
mouse_accel_profile=1
mouse_accel_speed=-0.66
mouse_natural_scrolling=0

# Touchpad
tap_to_click=1
trackpad_natural_scrolling=1
scroll_method=1
click_method=2
trackpad_accel_speed=0.3
disable_while_typing=1
middle_button_emulation=1

# ============================================
# AUTOSTART
# ============================================
exec-once=~/.config/mango/autostart.sh

# ==========================================
# MODULOS EXTERNOS (Rutas Absolutas)
# ==========================================
source=./conf.d/appearance.conf
source=./conf.d/windows.conf
source=./conf.d/keybinds.conf
source=./conf.d/workspaces.conf

# Noctalia config extra
source=./noctalia.conf
tearing=2
