include=~/.config/foot/themes/noctalia

[main]
#font=FiraCode Nerd Font:size=11.3
font=Maple Mono NF:size=11
# font=CozetteVector:size=13

pad=15x15 center
dpi-aware=no
box-drawings-uses-font-glyphs=no

[cursor]
style=block
blink=yes

[mouse]
hide-when-typing=yes

[csd]
size=0
border-width=0

[key-bindings]
scrollback-up-page=Shift+Page_Up
scrollback-down-page=Shift+Page_Down
clipboard-copy=Control+Shift+c
clipboard-paste=Control+Shift+v
search-start=Control+Shift+r
font-increase=Control+plus Control+equal
font-decrease=Control+minus
font-reset=Control+0
spawn-terminal=Control+Shift+n

[tweak]
grapheme-shaping=no
grapheme-width-method=wcswidth
sixel=yes
