# ==========================================
# APARIENCIA GENERAL (Bordes, Gaps, Sombras y Efectos)
# ==========================================

# ------------------------------------------
# BORDES Y GAPS
# ------------------------------------------
borderpx=1
gappih=5
gappiv=5
gappoh=25
gappov=25
smartgaps=0
no_border_when_single=0
#border_radius=0

# ------------------------------------------
# COLORES Y OPACIDAD
# ------------------------------------------
focused_opacity=0.96
unfocused_opacity=0.96


# ------------------------------------------
# BLUR (DIFUMINADO)
# ------------------------------------------
blur=1
blur_optimized=1
blur_params_num_passes=4
blur_params_radius=10
blur_params_noise=0.02
blur_params_brightness=0.95
blur_params_contrast=1.1
blur_params_saturation=1.2
blur_layer=1

# ------------------------------------------
# SOMBRAS
# ------------------------------------------
shadows=1
shadows_size=4
shadows_blur=20
shadows_position_y=5
shadows_position_x=0
shadowscolor=0x000000ff
layer_shadows=1
shadow_only_floating=0

# ------------------------------------------
# ANIMACIONES
# ------------------------------------------
animations=0
layer_animations=1
animation_duration_open=800
animation_duration_close=800
animation_duration_focus=600
animation_duration_move=700
animation_duration_tag=700
animation_fade_in=1
animation_fade_out=1

# ------------------------------------------
# MISCELÁNEOS (OTROS)
# ------------------------------------------
cursor_hide_timeout=10
xwayland_persistence=0
