# ==================================================
# REGLAS DE VENTANAS Y LAYERS
# ==================================================
windowrule=isfloating:1,appid:pavucontrol
windowrule=isfloating:1,appid:blueman-manager
windowrule=isfloating:1,appid:nm-connection-editor
windowrule=isfloating:1,appid:thunar,title:File Operation Progress
windowrule=isfloating:1,title:File Operation Progress
windowrule=isfloating:1,title:Picture-in-Picture

# pcmanfm-qt dialogs and operations
windowrule=isfloating:1,appid:pcmanfm-qt,title:(?i)(preferencias|propiedades|copiar|mover|eliminar|confirmar|file operation|properties|preferences|ejecutar archivo)
windowrule=noblur:1,isfullscreen:1
windowrule=noblur:1,appid:hl_linux

# ==================================================
# LAYER RULES
# ==================================================
layerrule=noanim:1,noblur:1,layer_name:selection
layerrule=noanim:1,noblur:1,layer_name:slurp
layerrule=noanim:1,noshadow:1,layer_name:swaync
layerrule=animation_type_open:fade,animation_type_close:fade,noshadow:1,noblur:1,layer_name:noctalia
