# ==========================================
# APARIENCIA GENERAL (Bordes, Gaps, Sombras y Efectos)
# ==========================================
borderpx=1
gappih=8
gappiv=8
gappoh=20
gappov=20
smartgaps=0
no_border_when_single=0
cursor_hide_timeout=10
border_radius=0
blur=1
blur_optimized=1
blur_params_num_passes=3
blur_params_radius=6
blur_params_noise=0.00
blur_params_brightness=1.0
blur_params_contrast=1.0
blur_params_saturation=1.0
shadows=1
shadows_blur=20
focused_opacity=0.96
unfocused_opacity=0.96
focuscolor=0xa7c080ff
bordercolor=0x57656cff
urgentcolor=0xe67e80ff
rootcolor=0x161616ff
xwayland_persistence=0

blur_layer=0
layer_shadows=0
layer_animations=0
animations=0
