# window border
window.active.border.color: #8ba37e
window.inactive.border.color: #a69680

# ToggleKeybinds status indicator
window.active.indicator.toggled-keybind.color: #c6685d

# window titlebar background
window.active.title.bg.color: #8ba37e
window.inactive.title.bg.color: #a69680

window.active.label.text.color: #242120
window.inactive.label.text.color: #242120
window.label.text.justify: center

# window button hover overlay
window.button.hover.bg.color: #413b38

# window buttons
window.active.button.unpressed.image.color: #242120
window.inactive.button.unpressed.image.color: #242120

# menu
menu.border.color: #242120
menu.items.bg.color: #8ba37e
menu.items.text.color: #242120
menu.items.active.bg.color: #a69680
menu.items.active.text.color: #242120
menu.separator.color: #242120
menu.title.bg.color: #8ba37e
menu.title.text.color: #242120

# on screen display (window-cycle dialog)
osd.bg.color: #8ba37e
osd.border.color: #242120
osd.label.text.color: #242120
osd.window-switcher.preview.border.color: #746965
