# ~/.config/sway/conf.d/autostart.conf

exec dbus-update-activation-environment --all
exec dbus-update-activation-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway QT_QPA_PLATFORMTHEME=qt6ct

exec pipewire &
exec wireplumber &
exec pipewire-pulse &

exec noctalia

exec_always autotiling

#exec otd-daemon
