# ~/.config/sway/conf.d/windows.conf


for_window [app_id="pavucontrol"] floating enable
for_window [app_id="blueman-manager"] floating enable
for_window [app_id="nm-connection-editor"] floating enable
for_window [app_id="thunar" title="File Operation Progress"] floating enable
for_window [app_id="pcmanfm-qt" window_type="dialog"] floating enable
for_window [app_id="pcmanfm-qt" window_role="pop-up"] floating enable
for_window [app_id="pcmanfm-qt" window_role="task_dialog"] floating enable
for_window [app_id="pcmanfm-qt" title="(?i)(preferencias|propiedades|copiar|mover|eliminar|confirmar|file operation|properties|preferences|ejecutar archivo)"] floating enable
for_window [class="(?i)pcmanfm-qt" window_type="dialog"] floating enable
for_window [class="(?i)pcmanfm-qt" window_role="pop-up"] floating enable
for_window [class="(?i)pcmanfm-qt" title="(?i)(preferencias|propiedades|copiar|mover|eliminar|confirmar|file operation|properties|preferences)"] floating enable

for_window [title="Picture-in-Picture"] floating enable, sticky enable
for_window [title="Picture-in-Picture"] inhibit_idle visible

for_window [app_id="chromium"] inhibit_idle fullscreen
for_window [app_id="librewolf"] inhibit_idle fullscreen

layer_effects "noctalia-bar-taskbar" {
  shadows enable;
  blur enable;
  blur_xray disable;
  blur_ignore_transparent enable;
}

layer_effects "noctalia-dock" {
  shadows disable;
  blur enable;
  blur_xray disable;
  blur_ignore_transparent enable;
}
